name: FOSSA License Scan

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  fossa-scan:
    if: github.repository == 'open-cluster-management-io/argocd-pull-integration'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run FOSSA Scan
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
