name: GoRelease

on:
  push:
    tags:
      - 'v*.*.*'
env:
  # Common versions
  GO_VERSION: '1.19'
  GO_REQUIRED_MIN_VERSION: ''
  GOPATH: '/home/runner/work/argocd-pull-integration/argocd-pull-integration/go'
  GITHUB_REF: ${{ github.ref }}

defaults:
  run:
    working-directory: go/src/github.com/open-cluster-management-io/argocd-pull-integration

jobs:
  release:
    if: github.repository == 'open-cluster-management-io/argocd-pull-integration'
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/github.com/open-cluster-management-io/argocd-pull-integration
      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.3
      - name: images
        run:  make docker-build
      - name: get release version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: get major release version
        run: |
          echo "MAJOR_RELEASE_VERSION=${RELEASE_VERSION%.*}" >> $GITHUB_ENV
      - name: push image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker tag quay.io/open-cluster-management/argocd-pull-integration:latest quay.io/open-cluster-management/argocd-pull-integration:$RELEASE_VERSION
          docker push quay.io/open-cluster-management/argocd-pull-integration:$RELEASE_VERSION
      - name: generate changelog
        run: |
          echo "# argocd-pull-integration $RELEASE_VERSION" > /home/runner/work/changelog.txt
          echo "- The released image is quay.io/open-cluster-management/argocd-pull-integration:$RELEASE_VERSION" >> /home/runner/work/changelog.txt
      - name: publish release
        uses: softprops/action-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: /home/runner/work/changelog.txt
